### ISSUE TITLE
rubber-info returns "there was no error", yet knap won't run textopdf or previewer

### ISSUE THREAD

**Issue by justinvson-pd** [frabjous/knap#30]
I installed knap using lazyvim, this is in my init.lua:
```
local gknapsettings = {
    texoutputext = "pdf",
    textopdf = "nix-shell -p steam-run --run \"make\"",
    textopdfviewerlaunch = "okular %outputfile%",
    textopdfviewerrefresh = "kill -HUP %pid%",
    textopdfshorterror = "A=%outputfile% ; LOGFILE=\"${A%.pdf}.log\" ; env --chdir=latex.out -S rubber-info \"$LOGFILE\" 2>&1 | head -n 1", -- output files are put in latex.out directory, so chdir there before running rubber-info
}
vim.g.knap_settings = gknapsettings

-- set shorter name for keymap function
local kmap = vim.keymap.set

-- F5 processes the document once, and refreshes the view
kmap({ 'n', 'v', 'i' },'<F5>', function() require("knap").process_once() end)

-- F6 closes the viewer application, and allows settings to be reset
kmap({ 'n', 'v', 'i' },'<F6>', function() require("knap").close_viewer() end)

-- F7 toggles the auto-processing on and off
kmap({ 'n', 'v', 'i' },'<F7>', function() require("knap").toggle_autopreviewing() end)

-- F8 invokes a SyncTeX forward search, or similar, where appropriate
kmap({ 'n', 'v', 'i' },'<F8>', function() require("knap").forward_jump() end)
```

No matter how I change the rubber-info command, it will always say "ERR: There was no error", and then stop, it won't do anything else. I can run the textopdf command, the textopdfviewerlaunch  and the textopdfshorterror commands all fine separate from each other.

rubber-info also seems to return 0, and pipes stderr to stdout, so how does knap see if there is an error at all? If I make the message "disappear" by adding grep -iv "there was no error", it will just output "ERR:".

**Comment by frabjous** [comment]
KNAP displays the output of the ...shorterror setting whenever the main processing command (here textopdf) returns a non-zero exit value.  I can't test yours because I'm not on NixOS and even if I were, I don't know how your makefiles work. If the the main command is exiting with a non-zero value, but there's no error in the LaTeX log, then what you're seeing is what I'd expect.

The exit-value of the shorterror command doesn't matter for anything.

Unrelated, but Okular automatically reloads changed files. There's no need to send the HUP signal; you can change that setting to "none".

**Comment by justinvson-pd** [comment]
Ah, okay. Seems my main command does exit with a non 0 exit code since latexrun (which is what is ran in the makefile) fails within the steam-run environment, guess that's because biber is missing a library. However, it DOES rebuild the PDF by running pdflatex, but I guess knap relies on the return code. I'll see if I can fix latexrun , or just make it return 0. Thanks for the input.
