### ISSUE TITLE
rubber-info: command not found

### ISSUE THREAD

**Issue by barungh** [frabjous/knap#5]
I am getting this error, when I press F5 or F7

![Screenshot_2022-06-11-09-30-56_1366x768](https://user-images.githubusercontent.com/12285528/173171833-15aab31c-a995-4c7c-88f0-d9aaafe85e1f.png)

Thank you for your great work

**Comment by barungh** [comment]
Installing rubber package solved this issue

**Comment by frabjous** [comment]
Thanks. I edited the README to mention that rubber is used by the default configuration, though of course you can configure another option for textopdfshorterror if you want to use a different tool for error reporting. (And I assume you figured out you have a double backslash in `\\begin{document}` which is why it was invoking error reporting, and of course that may have just been deliberate.)
