### ISSUE TITLE
global functions

### ISSUE THREAD

**Issue by anuvyklack** [frabjous/knap#8]
You define all your functions as global. In Lua local functions defines like this:

```lua
local function funname(param)
   ...
end
```
Pleasure make them local, because they interfere in my environment.

**Comment by frabjous** [comment]
Thanks. I thought I had fixed this but apparently I had only added their names to the return value without declaring them locally. I can't use the syntax `local function funcname(param)` because that would make it difficult to have them call each other without attaching them all to a table which I'm too lazy to do, so what I've done instead is use `local funcname1, funcname2, ...` at the beginning of the script, which should prevent the function names from polluting the global environment. But if you have further troubles, do let me know.
