### ISSUE TITLE
Prevent constant buffer writing

### ISSUE THREAD

**Issue by RaafatTurki** [frabjous/knap#9]
Hi, great plugin!
In the readme there's this section that explain exactly what this issue is about:

> Warning: Part of the way this works is that your file is constantly saved, with its usual filename. This may be dangerous for some people’s workflow, especially those who don’t make adequate backups. Take care not to save over important work if you don't have a way to get it back (e.g., a previous git commit).

I'll be speaking mainly in the context of latex previewing however this applies in every other pipeline.
My suggestion is to copy the buffer contents "constantly" into a temp file in `vim.fn.stdpath('cache') .. '/knap'` and use that for processing,.

With that change we:
- no longer have to save the actual file the user is editing (not all users have that luxury, especially in remote environments)
- no longer have build artifacts reside in the users directory (latex generate up to 5 `.aux, .lof, .log, .pdf, .synctex.gz`)

This also opens the door to implement things like:
- Inject something into the source file before processing if need be
- Have the previewer not break even if we rename the file
- A cleaner builtin implementation of [this](https://github.com/frabjous/knap#troubleshooting-and-workarounds)

LMK what you think.

**Comment by frabjous** [comment]
It's not a bad idea and I've thought about something like this. The problem is that it becomes very unworkable if you have a complex project with subfiles and/or a different document root. You'd have to create a cached copy not just of the buffer but of all included files, master files, other files included by master files, images, fonts, bibtex files, local packages, etc., and/or somehow accommodate for the change in path if relative paths for them are used – and once you changed the source file by allowing injections like you suggest, or even simple path changes like the ones described, either synctex would stop working altogether (as line numbers wouldn't match) or you'd have to implement fairly sophisticated logic to accommodate the changes.

The problem is just as bad for formats like HTML where other files are almost always used in the output.

If someone wants to try their hand at solving all those issues, good luck to them. I'd even consider a PR here.  But I don't think it's something I'm all that interested in working on. For me, I consider my git commits my true "saves", and just accept that the file I'm working on is always going to be in flux. I want to see its actual output, not the output of some temporary stand in.

**Comment by RaafatTurki** [comment]
I see, yes this introduces too much complexity as I didn't account for multi file projects.

My point still mostly stands in single file projects but I think I've got a better solution, forget about making a temp copy what about heredocs?

In bash we can do something like the following
```bash
cat << EOF
The current working directory is: $PWD
You are logged in as: $(whoami)
EOF
```
From the perspective of cat it's catting a normal file as if it was `cat ./sample.txt`
 
I believe we can leverage that to feed the file into the processing pipeline without saving it.

**Comment by RaafatTurki** [comment]
I've realized the snipped I gave is piping the file through stdin, Here's a better example that fits our use case:
```bash
python /dev/fd/3 3<< 'EOF'
print("Hello World")
EOF
```
we're using a file descriptor above 2 so python can still use stdin/stdout/stderr unaffected.

**Comment by frabjous** [comment]
I suppose it might not be too hard to add an option, which, if activated, would send the contents of the current buffer as stdin to the processing command, rather than saving the buffer. All the various flavors of latex, as well as pandoc, etc., are happy to read from stdin. I'll give this some thought.

I probably wouldn't make it default, or use it myself, because I think it would still break SyncTeX, which tracks things by the input filename.

It would be possible probably to just put a redirection to another file descriptor in the processing command if that were necessary, but it was kind of unclear to me why you wouldn't just use stdin. Is the kind of thing I describe above adequate for your use case?

**Comment by RaafatTurki** [comment]
In an ideal world every utility under the sun would adhere to the UNIX philosophy and be able to function the same way regardless of how the input is being provided. however I'm sure that's not the case hence the heredoc workaround I've alluded to.

> because I think it would still break SyncTeX

Yes synctex would most likely break.

> Is the kind of thing I describe above adequate for your use case?

It's decent.

**Comment by frabjous** [comment]
I've added a buffer-as-stdin option, which will send the current buffer contents as stdin to the routine's processing command if `[routine]bufferasstdin` is set, and set to true, and won't save the file to its usual filename. E.g., for a `textopdf` routine, you could put:

```lua
local gnapsettings = {
    textopdf = "pdflatex -jobname \"$(basename -s .pdf %outputfile%)\" -halt-on-error",
    textopdfbufferasstdin = true
}
vim.g.knap_settings = gknapsettings
```
(Of course the routine's processing command, here `textopdf =` is also changed so that it could use stdin rather passing the filename.)

More details in the updated readme [here](https://github.com/frabjous/knap/#using-buffer-as-stdin-rather-than-saving).

You can of course redirect (using something like `cat > temporary-file && ...`) to save and process a temporary file instead.

It won't cover all possible use cases, but if yours is more complex, a custom script or plugin might be better anyway.
